version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "5432:5432"

  django:
    build: ./denv
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./denv:/denv
    ports:
      - "8000:8000"
    depends_on:
      - db